name: mission-tool-dev
channels:
  - conda-forge
dependencies:
  - python=3.13
  - pykep=3.0.0
  - streamlit=1.61.1
  - pandas=3.0.5
  - numpy=2.5.2
  - plotly=6.9.0
  - fpdf2=2.8.7
  - pip
  - pip:
      - -r requirements-dev.txt
